import { Key } from '@nut-tree-fork/nut-js';

// WebSocket 命令常量
export const WS_COMMAND = {
  // 认证
  AUTH: 'auth',
  AUTH_RESULT: 'auth_result',
  AUTH_REQUIRED: 'auth_required',
  READY: 'ready',

  // 屏幕
  CAPTURE_FRAME: 'capture_frame',
  START_STREAM: 'start_stream',
  STOP_STREAM: 'stop_stream',
  FRAME: 'frame',
  STREAM_STARTED: 'stream_started',
  STREAM_STOPPED: 'stream_stopped',
  GET_SCREEN_INFO: 'get_screen_info',
  SCREEN_INFO: 'screen_info',

  // 鼠标
  MOUSE_MOVE: 'mouse_move',
  MOUSE_LEFT_CLICK: 'mouse_left_click',
  MOUSE_RIGHT_CLICK: 'mouse_right_click',
  MOUSE_DOUBLE_CLICK: 'mouse_double_click',
  MOUSE_PRESS_LEFT: 'mouse_press_left',
  MOUSE_RELEASE_LEFT: 'mouse_release_left',
  MOUSE_DRAG: 'mouse_drag',
  MOUSE_SCROLL: 'mouse_scroll',
  GET_MOUSE_POSITION: 'get_mouse_position',
  MOUSE_POSITION: 'mouse_position',

  // 键盘
  KEYBOARD_TYPE: 'keyboard_type',
  KEYBOARD_PRESS: 'keyboard_press',
  KEYBOARD_RELEASE: 'keyboard_release',

  // 响应
  RESPONSE: 'response',
} as const;

// 键盘映射表 - 从 billd-desk 复用
export const NUT_KEY_MAP: Record<string, Key> = {
  A: Key.A,
  B: Key.B,
  C: Key.C,
  D: Key.D,
  E: Key.E,
  F: Key.F,
  G: Key.G,
  H: Key.H,
  I: Key.I,
  J: Key.J,
  K: Key.K,
  L: Key.L,
  M: Key.M,
  N: Key.N,
  O: Key.O,
  P: Key.P,
  Q: Key.Q,
  R: Key.R,
  S: Key.S,
  T: Key.T,
  U: Key.U,
  V: Key.V,
  W: Key.W,
  X: Key.X,
  Y: Key.Y,
  Z: Key.Z,
  '0': Key.Num0,
  '1': Key.Num1,
  '2': Key.Num2,
  '3': Key.Num3,
  '4': Key.Num4,
  '5': Key.Num5,
  '6': Key.Num6,
  '7': Key.Num7,
  '8': Key.Num8,
  '9': Key.Num9,
  Fn: Key.Fn,
  F1: Key.F1,
  F2: Key.F2,
  F3: Key.F3,
  F4: Key.F4,
  F5: Key.F5,
  F6: Key.F6,
  F7: Key.F7,
  F8: Key.F8,
  F9: Key.F9,
  F10: Key.F10,
  F11: Key.F11,
  F12: Key.F12,
  F13: Key.F13,
  F14: Key.F14,
  F15: Key.F15,
  F16: Key.F16,
  F17: Key.F17,
  F18: Key.F18,
  F19: Key.F19,
  F20: Key.F20,
  F21: Key.F21,
  F22: Key.F22,
  F23: Key.F23,
  F24: Key.F24,
  Delete: Key.Delete,
  Enter: Key.Enter,
  Space: Key.Space,
  Backspace: Key.Backspace,
  ShiftLeft: Key.LeftShift,
  ShiftRight: Key.RightShift,
  AltLeft: Key.LeftAlt,
  AltRight: Key.RightAlt,
  Tab: Key.Tab,
  Backquote: Key.Quote,
  Backslash: Key.Backslash,
  ArrowUp: Key.Up,
  ArrowDown: Key.Down,
  ArrowLeft: Key.Left,
  ArrowRight: Key.Right,
  CapsLock: Key.CapsLock,
  ControlLeft: Key.LeftControl,
  ControlRight: Key.RightControl,
  MetaLeft: Key.LeftCmd,
  LeftCmd: Key.LeftCmd,
  MetaRight: Key.RightCmd,
  RightCmd: Key.RightCmd,
  LeftWin: Key.LeftWin,
  RightWin: Key.RightWin,
};

// 默认配置
export const DEFAULT_CONFIG = {
  wsPort: 9876,
  httpPort: 9877,
  password: 'admin123',
};
